export {
  SWING_STRUCTURE_VERSION,
  DEFAULT_SWING_STRUCTURE_CONFIG,
  evaluateSwingStructure,
  emptySwingStructure,
  detectConfirmedSwings,
  detectPendingSwings,
  completedSwingBars,
  filterNoiseSwings,
  updateSwingStates,
  classifyStructureSequence,
  selectRecentSwings,
  classifySwingLocation,
  classifySwingInteraction,
  detectBosChoch,
  swingHistoricalConfluence,
  swingLiveConfluence,
  scoreSignificance,
  distanceBps,
  effectiveNearBps,
  mergeSwingConfig,
  swingLocationBadge,
} from './engine.js';
export type {
  SwingStructureSnapshot,
  SwingPoint,
  SwingBarLike,
  SwingStructureConfig,
  SwingCurrentContext,
  SwingType,
  SwingClass,
  SwingState,
  StructureState,
  StructureStep,
  SwingLocationState,
  SwingInteractionState,
  BosChochEvent,
  SwingHistoricalConfluence,
  SwingLiveConfluence,
  SwingSignificanceComponents,
  EvaluateSwingStructureInput,
} from './engine.js';
