export {
  FAILURE_RECLAIM_VERSION,
  DEFAULT_FAILURE_RECLAIM_CONFIG,
  evaluateFailureReclaim,
  emptyFailureReclaim,
  pickReferenceLevels,
  classifyBreakAttempt,
  classifyFailure,
  classifyReclaim,
  classifyControlShift,
  minBreakDistance,
  distanceBps,
  mergeFailureReclaimConfig,
  failureReclaimBadge,
  failureReclaimCard,
} from './engine.js';
export type {
  FailureReclaimSnapshot,
  ReferenceLevel,
  ReferenceLevelType,
  SetupMachineState,
  SetupAction,
  FailedSide,
  ReclaimQuality,
  ControlShiftState,
  MissingConfirmation,
  FlowEvidence,
  BarLike,
  BreakAttemptView,
  FailureView,
  ReclaimView,
  ControlShiftView,
  SetupConfidenceComponents,
  FailureReclaimAlert,
  FailureReclaimConfig,
  EvaluateFailureReclaimInput,
} from './engine.js';
