import type { PatternDefinition } from './pattern-types.js';

export const PATTERN_LIBRARY_VERSION = 1;

export const PATTERN_DEFINITIONS: PatternDefinition[] = [
  {
    id: 'BULLISH_LIQUIDITY_REVERSAL',
    version: PATTERN_LIBRARY_VERSION,
    direction: 'BULLISH',
    title: 'Bullish Liquidity Reversal',
    badge: 'BR',
    minBars: 4,
    maxBars: 6,
    specificity: 80,
    supersedes: ['SELLER_TRAP_FORMING'],
    minFormingStages: 2,
    failWhen: { minStage: 2, labels: ['SELLER_IN_CONTROL', 'BUYER_ABSORBED'] },
    stages: [
      { labels: ['SELLER_IN_CONTROL'], repeat: true },
      { labels: ['BIDS_PULLED'], optional: true },
      { labels: ['STOP_HUNT_LOW'] },
      { labels: ['BIDS_PULLED'], optional: true },
      { labels: ['SELLER_ABSORBED'] },
      { labels: ['BUYER_IN_CONTROL'] },
    ],
  },
  {
    id: 'BEARISH_LIQUIDITY_REVERSAL',
    version: PATTERN_LIBRARY_VERSION,
    direction: 'BEARISH',
    title: 'Bearish Liquidity Reversal',
    badge: 'ER',
    minBars: 4,
    maxBars: 6,
    specificity: 80,
    supersedes: ['BUYER_TRAP_FORMING'],
    minFormingStages: 2,
    failWhen: { minStage: 2, labels: ['BUYER_IN_CONTROL', 'SELLER_ABSORBED'] },
    stages: [
      { labels: ['BUYER_IN_CONTROL'], repeat: true },
      { labels: ['ASKS_PULLED'], optional: true },
      { labels: ['STOP_HUNT_HIGH'] },
      { labels: ['ASKS_PULLED'], optional: true },
      { labels: ['BUYER_ABSORBED'] },
      { labels: ['SELLER_IN_CONTROL'] },
    ],
  },
  {
    id: 'BULLISH_CONTINUATION',
    version: PATTERN_LIBRARY_VERSION,
    direction: 'BULLISH',
    title: 'Bullish Continuation',
    badge: 'BC',
    minBars: 3,
    maxBars: 6,
    specificity: 50,
    minFormingStages: 2,
    failWhen: { minStage: 2, labels: ['SELLER_IN_CONTROL', 'BUYER_ABSORBED'] },
    stages: [
      { labels: ['BUYER_IN_CONTROL'], repeat: true },
      { labels: ['ASKS_PULLED'], repeat: true },
      { labels: ['BUYER_IN_CONTROL'], repeat: true },
    ],
  },
  {
    id: 'BEARISH_CONTINUATION',
    version: PATTERN_LIBRARY_VERSION,
    direction: 'BEARISH',
    title: 'Bearish Continuation',
    badge: 'SC',
    minBars: 3,
    maxBars: 6,
    specificity: 50,
    minFormingStages: 2,
    failWhen: { minStage: 2, labels: ['BUYER_IN_CONTROL', 'SELLER_ABSORBED'] },
    stages: [
      { labels: ['SELLER_IN_CONTROL'], repeat: true },
      { labels: ['BIDS_PULLED'], repeat: true },
      { labels: ['SELLER_IN_CONTROL'], repeat: true },
    ],
  },
  {
    id: 'FAILED_BEARISH_REVERSAL',
    version: PATTERN_LIBRARY_VERSION,
    direction: 'BULLISH',
    title: 'Failed Bearish Reversal',
    badge: 'FB',
    minBars: 3,
    maxBars: 5,
    specificity: 70,
    minFormingStages: 2,
    failWhen: { minStage: 2, labels: ['SELLER_IN_CONTROL'] },
    stages: [
      { labels: ['STOP_HUNT_HIGH'] },
      { labels: ['SELLER_IN_CONTROL'], repeat: true },
      { labels: ['BUYER_IN_CONTROL'] },
    ],
  },
  {
    id: 'FAILED_BULLISH_REVERSAL',
    version: PATTERN_LIBRARY_VERSION,
    direction: 'BEARISH',
    title: 'Failed Bullish Reversal',
    badge: 'FU',
    minBars: 3,
    maxBars: 5,
    specificity: 70,
    minFormingStages: 2,
    failWhen: { minStage: 2, labels: ['BUYER_IN_CONTROL'] },
    stages: [
      { labels: ['STOP_HUNT_LOW'] },
      { labels: ['BUYER_IN_CONTROL'], repeat: true },
      { labels: ['SELLER_IN_CONTROL'] },
    ],
  },
  {
    id: 'BUYER_TRAP_FORMING',
    version: PATTERN_LIBRARY_VERSION,
    direction: 'BEARISH',
    title: 'Buyer Trap Forming',
    badge: 'BT',
    minBars: 3,
    maxBars: 6,
    specificity: 40,
    completesOnMatch: false,
    minFormingStages: 3,
    failWhen: { minStage: 2, labels: ['BUYER_IN_CONTROL'] },
    stages: [
      { labels: ['BUYER_IN_CONTROL'], repeat: true },
      { labels: ['ASKS_PULLED'], optional: true },
      { labels: ['STOP_HUNT_HIGH'] },
      { labels: ['ASKS_PULLED'], optional: true },
      { labels: ['BUYER_ABSORBED'] },
    ],
  },
  {
    id: 'SELLER_TRAP_FORMING',
    version: PATTERN_LIBRARY_VERSION,
    direction: 'BULLISH',
    title: 'Seller Trap Forming',
    badge: 'SR',
    minBars: 3,
    maxBars: 6,
    specificity: 40,
    completesOnMatch: false,
    minFormingStages: 3,
    failWhen: { minStage: 2, labels: ['SELLER_IN_CONTROL'] },
    stages: [
      { labels: ['SELLER_IN_CONTROL'], repeat: true },
      { labels: ['BIDS_PULLED'], optional: true },
      { labels: ['STOP_HUNT_LOW'] },
      { labels: ['BIDS_PULLED'], optional: true },
      { labels: ['SELLER_ABSORBED'] },
    ],
  },
];

export function patternVersionTag(id: string, version: number): string {
  return `${id}:v${version}`;
}

export function requiredStageCount(def: PatternDefinition): number {
  return def.stages.filter((s) => !s.optional).length;
}
